// Code generated by tools/python/generate_cvnss_go.py; DO NOT EDIT.

package core

const CVNSSRuleVersion = "5.1.0-bilakey-core"

const CVNSSBaseRows = 758

const CVNSSPatchEntries = 336

const CVNSSAmbiguityGroups = 56

const CVNSSCanonicalPolicies = 56

const CVNSSCriticalCollisionGroups = 5

var cvnssToCQN = make(map[string]string, 810)

var cvnToCQN = cvnssToCQN

var cvnssCandidates = map[string][]string{
	"ed":  {"ề", "oet"},
	"es":  {"ẽ", "oec"},
	"i":   {"i", "y"},
	"iaj": {"ía", "ýa"},
	"ial": {"ìa", "ỳa"},
	"iar": {"ịa", "ỵa"},
	"ias": {"ĩa", "ỹa"},
	"iaz": {"ỉa", "ỷa"},
	"idb": {"iết", "yết"},
	"idd": {"iềt", "yềt"},
	"idf": {"iệt", "yệt"},
	"idg": {"iễt", "yễt"},
	"idq": {"iểt", "yểt"},
	"idy": {"yêt", "iêt"},
	"ij":  {"í", "ý"},
	"il":  {"ì", "ỳ"},
	"ilb": {"iến", "yến"},
	"ild": {"iền", "yền"},
	"ilf": {"iện", "yện"},
	"ilg": {"iễn", "yễn"},
	"ilq": {"iển", "yển"},
	"ily": {"iên", "yên"},
	"ir":  {"ị", "ỵ"},
	"is":  {"ĩ", "ỹ"},
	"ivb": {"iếm", "yếm"},
	"ivd": {"iềm", "yềm"},
	"ivf": {"iệm", "yệm"},
	"ivg": {"iễm", "yễm"},
	"ivq": {"iểm", "yểm"},
	"ivy": {"iêm", "yêm"},
	"iwb": {"iếu", "yếu"},
	"iwd": {"iều", "yều"},
	"iwf": {"iệu", "yệu"},
	"iwg": {"iễu", "yễu"},
	"iwq": {"iểu", "yểu"},
	"iwy": {"iêu", "yêu"},
	"iz":  {"ỉ", "ỷ"},
	"izb": {"iếng", "yếng"},
	"izd": {"iềng", "yềng"},
	"izf": {"iệng", "yệng"},
	"izg": {"iễng", "yễng"},
	"izq": {"iểng", "yểng"},
	"izy": {"iêng", "yêng"},
	"oaj": {"óa", "oá"},
	"oal": {"òa", "oà"},
	"oar": {"ọa", "oạ"},
	"oas": {"õa", "oã"},
	"oaz": {"ỏa", "oả"},
	"od":  {"ồ", "oat"},
	"of":  {"ộ", "oap"},
	"os":  {"õ", "oac"},
	"yj":  {"úy", "uý"},
	"yl":  {"ùy", "uỳ"},
	"yr":  {"ụy", "uỵ"},
	"ys":  {"ũy", "uỹ"},
	"yz":  {"ủy", "uỷ"},
}

var cvnssCriticalCandidates = map[string][]string{
	"ed": {"ề", "oet"},
	"es": {"ẽ", "oec"},
	"od": {"ồ", "oat"},
	"of": {"ộ", "oap"},
	"os": {"õ", "oac"},
}

var codeInitials = []string{"ch", "nh", "th", "tr", "w", "f", "q", "k", "j", "g", "c", "z", "d", "b", "h", "l", "m", "n", "r", "s", "t", "v", "x"}
