#!/usr/bin/env python3
"""Generate BilaKey's auditable Go CVNSS tables from oracle 5.x.

The runtime keeps a deterministic canonical table for the hot path and a
candidate graph for inspection/cycling.  Generation fails closed when the
oracle's published audit invariants change.
"""
from __future__ import annotations

import argparse
import json
from collections import OrderedDict, defaultdict
from pathlib import Path


def load_rules(source: Path):
    """Load the modular, reviewable CVNSS rule dataset."""
    data_dir = source if source.is_dir() else source.parent / "cvnss"
    if not data_dir.is_dir():
        raise ValueError(f"cannot locate modular CVNSS data directory from {source}")

    def read(name: str):
        return json.loads((data_dir / name).read_text(encoding="utf-8"))

    base = []
    for item in sorted(data_dir.glob("base_[0-9][0-9].json")):
        base.extend(json.loads(item.read_text(encoding="utf-8")))
    patch54 = []
    for item in sorted(data_dir.glob("patch54_[0-9][0-9].json")):
        patch54.extend(json.loads(item.read_text(encoding="utf-8")))
    return {
        "metadata": read("metadata.json"),
        "base": base,
        "patch54": patch54,
        "patch56": read("patch56.json"),
        "initials": read("initials.json"),
        "preferred": read("canonical.json"),
        "critical": read("critical.json"),
    }

def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def go_map_string_string(name: str, values: dict[str, str]) -> str:
    lines = [f"var {name} = map[string]string{{"]
    for key in sorted(values):
        lines.append(f"\t{go_string(key)}: {go_string(values[key])},")
    lines.append("}")
    return "\n".join(lines)


def go_map_string_slice(name: str, values: dict[str, list[str]]) -> str:
    lines = [f"var {name} = map[string][]string{{"]
    for key in sorted(values):
        items = ", ".join(go_string(item) for item in values[key])
        lines.append(f"\t{go_string(key)}: {{{items}}},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("oracle", type=Path)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--out", type=Path)
    group.add_argument("--out-dir", type=Path)
    args = parser.parse_args()

    rules = load_rules(args.oracle)
    version = rules["metadata"]["version"]
    base = rules["base"]
    patch54 = rules["patch54"]
    patch56 = rules["patch56"]
    initials = rules["initials"]
    preferred = rules["preferred"]
    critical = rules["critical"]

    cvn_candidates: dict[str, list[str]] = defaultdict(list)
    cvss_candidates: dict[str, list[str]] = defaultdict(list)

    def add(index: dict[str, list[str]], code: str, cqn: str) -> None:
        if cqn not in index[code]:
            index[code].append(cqn)

    for cqn, cvn, cvss in base:
        add(cvn_candidates, cvn, cqn)
        add(cvss_candidates, cvss, cqn)
    for cqn, code in patch54 + patch56:
        add(cvn_candidates, code, cqn)
        add(cvss_candidates, code, cqn)

    ambiguity_count = sum(len(items) > 1 for items in cvss_candidates.values())
    if (len(base), len(patch54) + len(patch56), ambiguity_count, len(preferred), len(critical)) != (758, 336, 56, 56, 5):
        raise ValueError(
            "oracle audit invariant changed: "
            f"base={len(base)} patches={len(patch54)+len(patch56)} "
            f"ambiguities={ambiguity_count} policies={len(preferred)} critical={len(critical)}"
        )

    def select(index: dict[str, list[str]]) -> dict[str, str]:
        result: dict[str, str] = {}
        for code, candidates in index.items():
            choice = preferred.get(code, candidates[0])
            if choice not in candidates:
                raise ValueError(f"canonical policy {code}={choice!r} is not a candidate")
            result[code] = choice
        return result

    code_initials = list(OrderedDict.fromkeys(cvn for _, cvn in initials))
    code_initials.sort(key=lambda item: -len(item))
    cvn_selected = select(cvn_candidates)
    cvss_selected = select(cvss_candidates)
    if cvn_selected != cvss_selected:
        raise ValueError("CVN/CVSS selected tables diverged; runtime alias is no longer safe")

    if args.out_dir:
        out_dir = args.out_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        for old in out_dir.glob("cvnss_generated_*.go"):
            old.unlink()

        meta = [
            "// Code generated by tools/python/generate_cvnss_go.py; DO NOT EDIT.",
            "package core",
            f'const CVNSSRuleVersion = {go_string(version)}',
            f"const CVNSSBaseRows = {len(base)}",
            f"const CVNSSPatchEntries = {len(patch54) + len(patch56)}",
            f"const CVNSSAmbiguityGroups = {ambiguity_count}",
            f"const CVNSSCanonicalPolicies = {len(preferred)}",
            f"const CVNSSCriticalCollisionGroups = {len(critical)}",
            "var cvnssToCQN = make(map[string]string, 810)",
            "var cvnToCQN = cvnssToCQN",
            go_map_string_slice(
                "cvnssCandidates",
                {code: values for code, values in cvss_candidates.items() if len(values) > 1},
            ),
            go_map_string_slice("cvnssCriticalCandidates", critical),
            "var codeInitials = []string{" + ", ".join(go_string(x) for x in code_initials) + "}",
            "",
        ]
        (out_dir / "cvnss_generated_meta.go").write_text("\n\n".join(meta), encoding="utf-8", newline="\n")
        groups: dict[str, dict[str, str]] = defaultdict(dict)
        for code, value in cvss_selected.items():
            groups[code[0]].setdefault(code, value)
        for prefix in sorted(groups):
            lines = [
                "// Code generated by tools/python/generate_cvnss_go.py; DO NOT EDIT.",
                "package core",
                "func init() {",
            ]
            for code in sorted(groups[prefix]):
                lines.append(f"\tcvnssToCQN[{go_string(code)}] = {go_string(groups[prefix][code])}")
            lines.extend(["}", ""])
            (out_dir / f"cvnss_generated_{prefix}.go").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    else:
        chunks = [
            "// Code generated by tools/python/generate_cvnss_go.py; DO NOT EDIT.",
            "package core",
            f'const CVNSSRuleVersion = {go_string(version)}',
            f"const CVNSSBaseRows = {len(base)}",
            f"const CVNSSPatchEntries = {len(patch54) + len(patch56)}",
            f"const CVNSSAmbiguityGroups = {ambiguity_count}",
            f"const CVNSSCanonicalPolicies = {len(preferred)}",
            f"const CVNSSCriticalCollisionGroups = {len(critical)}",
            go_map_string_string("cvnssToCQN", cvss_selected),
            "var cvnToCQN = cvnssToCQN",
            go_map_string_slice(
                "cvnssCandidates",
                {code: values for code, values in cvss_candidates.items() if len(values) > 1},
            ),
            go_map_string_slice("cvnssCriticalCandidates", critical),
            "var codeInitials = []string{" + ", ".join(go_string(x) for x in code_initials) + "}",
            "",
        ]
        args.out.write_text("\n\n".join(chunks), encoding="utf-8", newline="\n")
    print(
        f"version={version} base={len(base)} patches={len(patch54)+len(patch56)} "
        f"codes={len(cvss_candidates)} ambiguities={ambiguity_count} policies={len(preferred)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
